apiVersion : apps/v1
kind: Deployment
metadata:
  name: 01testing 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 01testing
  template:
    metadata:
      labels:
        app: 01testing 
    spec:
      containers:
        - name: 01testing 
          image: azurepractice05.azurecr.io/01testing
          ports:
          - containerPort: 80